###
POST http://localhost:8080/api/pruebas

###
POST http://localhost:8080/api/login
Content-Type: application/json
Accept: application/json

{
  "nick": "emilio",
  "password": "1234"
}

###
POST http://localhost:8080/api/register
Content-Type: application/json
Accept: application/json

{
  "nick": "pruebas",
  "password": "1234",
  "correo": "prueba@gmail.com",
  "fechaNac": "2000-01-01"
}

###
GET http://localhost:8080/api/elo/{{nick}}/{{juego}}