name: Deploy en el servidor google cloud de la nueva version

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USER: ${{ secrets.SSH_USER }}
      SERVER_JAR_PATH: ${{ secrets.SERVER_JAR_PATH }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - name: Build server with Maven
        run: |
          cd Servidor-multijugador
          mvn clean package -DskipTests

      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy jar to server
        run: |
          scp Servidor-multijugador/target/Servidor-multijugador.jar $SSH_USER@$SSH_HOST:$SERVER_JAR_PATH

      - name: Restart server remotely
        run: |
          ssh $SSH_USER@$SSH_HOST "
            pkill -f 'java.*Servidor-multijugador.jar' || true
            nohup java -jar $SERVER_JAR_PATH > servidor.log 2>&1 &
          "
