name: Build and Package ClienteApp (Windows)

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - name: DEBUG - Mostrar contenido antes de crear config.properties
        run: dir Cliente-jfx\src\main\resources

      - name: Create config.properties
        run: |
          echo server.ip=${{ secrets.SERVER_IP }} > Cliente-jfx\src\main\resources\config.properties
          echo "Contenido generado:"
          type Cliente-jfx\src\main\resources\config.properties

      - name: DEBUG - Verificar que config.properties existe
        run: |
          if (Test-Path "Cliente-jfx\src\main\resources\config.properties") {
            Write-Host "✅ config.properties existe"
            Get-Content "Cliente-jfx\src\main\resources\config.properties"
          } else {
            Write-Host "❌ config.properties NO existe"
          }

      - name: Build with Gradle (cliente)
        run: |
          cd Cliente-jfx
          ./gradlew.bat clean fatJar

      - name: Prepare packaging folder
        run: |
          mkdir empaquetado
          copy Cliente-jfx\build\libs\*.jar empaquetado\ClienteApp.jar
          copy Cliente-jfx\src\main\resources\images\logoApp.ico empaquetado\icon.ico

      - name: DEBUG - Inspeccionar contenido del JAR
        run: |
          mkdir inspeccion
          cd inspeccion
          jar xf ..\empaquetado\ClienteApp.jar
          dir
          echo "✅ Archivo config.properties incluido:"
          type config.properties || echo "❌ config.properties NO se encuentra en el JAR"

      - name: Package app (.exe)
        shell: pwsh
        run: |
          jpackage `
          --type exe `
          --name ClienteApp `
          --input empaquetado `
          --main-jar ClienteApp.jar `
          --main-class MainApp `
          --win-shortcut `
          --win-menu `
          --icon empaquetado\icon.ico `
          --dest dist `
          --app-version 1.0

      - name: Upload .exe artifact
        uses: actions/upload-artifact@v4
        with:
          name: clienteapp-exe
          path: dist\*.exe
